# Generated by Django 5.2.9 on 2026-02-26 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=50)),
                ('work_setup', models.CharField(max_length=50)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('salary_range', models.CharField(max_length=100)),
                ('company_size', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('role_description', models.TextField(blank=True)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_color', models.CharField(default='#000000', max_length=50)),
            ],
        ),
    ]
